export interface City {
  id: number;
  name: string;
}

export interface GovernorateWithCities {
  id: string;
  name: string;
  cities: City[];
}

const GOVERNORATE_CITIES: Record<string, string[]> = {
  damascus: [
    "mazzeh",
    "kafrsouseh",
    "barzeh",
    "meidan",
    "ruken_al_din",
    "bab_touma",
    "bab_sharqi",
    "tishreen",
    "al_qanawat",
    "abu_rummaneh",
    "shaalan",
    "dummar",
    "al_midan",
    "kassaa",
    "old_damascus",
    "qasioun",
    "adawi",
    "al_amara",
    "abu_jamal",
    "harika",
  ],
  rural_damascus: [
    "douma",
    "harasta",
    "zamalka",
    "jobar",
    "qaboun",
    "madaya",
    "zabadani",
    "wafideen",
    "sayyida_zeinab",
    "darayya",
    "moadamiyeh",
    "qatana",
    "kiswah",
    "dmeir",
    "al_tall",
    "arbin",
    "haran_al_awamid",
    "yabroud",
    "an_nabk",
    "deir_atiyah",
    "jayrud",
    "assal_al_ward",
  ],
  aleppo: [
    "salah_al_din",
    "hanano",
    "ashrafiyeh",
    "aziziyeh",
    "seif_al_dawla",
    "al_furqan",
    "al_hamdaniya",
    "al_sukari",
    "al_shaar",
    "al_jamiliyeh",
    "karm_al_jabal",
    "al_midan",
    "sheikh_maqsood",
    "bustan_al_qasr",
    "al_aziziyah",
    "new_aleppo",
    "old_city",
    "sheikh_najjar",
    "khan_al_asal",
    "ramousah",
    "layramoun",
    "al_layramoun",
    "al_haydariyah",
  ],
  homs: [
    "al_inshaat",
    "al_waer",
    "al_hamra",
    "bab_tadmur",
    "al_khaldiyeh",
    "al_bayada",
    "deir_ba_alba",
    "ghouta",
    "al_qusur",
    "al_zahraa",
    "al_nuzha",
    "al_sabeel",
    "al_hamidiyah",
    "al_qarabis",
    "al_karama",
    "al_salam",
    "al_ghouta",
    "al_hosn",
    "al_qaryatein",
    "palmyra",
  ],
  hama: [
    "al_arbaeen",
    "al_nasiriya",
    "al_kareem",
    "al_saboun",
    "al_baath",
    "mhardeh",
    "slimiyah",
    "kafr_zita",
    "latamina",
    "taybat_al_imam",
    "soran",
    "kafr_nabudah",
    "halfaya",
    "maharda",
    "qamhana",
    "al_latamna",
    "al_surmaniyah",
    "al_mazzeh_hama",
    "al_suqailabiya",
    "al_hamraa",
  ],
  latakia: [
    "al_ramleh",
    "al_ziraa",
    "corniche",
    "qastal_maaf",
    "jableh",
    "qardaha",
    "slunfeh",
    "baniyas",
    "al_haffa",
    "al_sheikh_daher",
    "al_daatour",
    "ras_al_basit",
    "kessab",
    "al_sanamayn",
    "al_raml",
    "al_bayda",
    "al_shamiya",
    "al_kabir",
    "al_safa",
    "al_midan_latakia",
  ],
  tartous: [
    "tartous",
    "al_sheikh_badr",
    "baniyas",
    "corniche",
    "dreikish",
    "rabea",
    "mashta_al_hilou",
    "bechmira",
    "al_hamidiyah",
    "al_dreikish",
    "al_kadmous",
    "al_safsafah",
    "al_sheikh_badr_center",
    "al_tall",
    "al_kadmus",
    "al_rastan_tartous",
    "al_sudan",
    "al_sisiya",
    "al_bayada",
    "al_hamra_tartous",
  ],
  idlib: [
    "idlib",
    "maarret_al_numan",
    "saraqib",
    "khan_sheikhoun",
    "jisir_al_shughur",
    "binnish",
    "taftanaz",
    "araq",
    "sarmin",
    "kafr_nabl",
    "maaret_al_tamasrin",
    "harem",
    "darkosh",
    "salqin",
    "al_dana",
    "ram_hamdan",
    "kafr_aya",
    "kafr_sajna",
    "tal_karah",
    "zardana",
  ],
  daraa: [
    "daraa",
    "busra_al_sham",
    "nawa",
    "jasem",
    "tafss",
    "mzeireb",
    "sanamayn",
    "inkhilal",
    "hirak",
    "dael",
    "al_sheikh_maskin",
    "namir",
    "ghabgab",
    "al_yadouda",
    "al_tibneh",
    "tal_shihab",
    "khirbet_ghazaleh",
    "al_harak",
    "al_jiza",
    "al_manshiya",
  ],
  deir_ezzor: [
    "deir_ezzor",
    "al_mayadeen",
    "al_bukamal",
    "al_busayra",
    "al_susah",
    "khasham",
    "al_husseiniyah",
    "al_jura",
    "al_quriya",
    "al_hawayej",
    "al_tayana",
    "al_tabni",
    "al_shuhail",
    "al_abu_kamal",
    "al_husainiya",
    "al_jezira",
    "al_dhula",
    "al_baghouz",
    "al_salihiyah",
    "al_omar",
  ],
  raqqa: [
    "raqqa",
    "tal_abyad",
    "al_tabqa",
    "al_mansoura",
    "al_karamah",
    "al_karama",
    "al_hanida",
    "al_kasrat",
    "al_resh",
    "al_hisba",
    "al_rashid",
    "al_jurneyyah",
    "al_sabkha",
    "al_hol",
    "al_rasafa",
    "al_sharakrak",
    "al_khafsa",
    "al_masrab",
    "al_tabaqa_dam",
    "al_qadisiya",
  ],
  hasakah: [
    "qamishli",
    "hasakah",
    "malikiya",
    "ras_al_ayn",
    "al_shaddadi",
    "amuda",
    "derbasiya",
    "tirbespi",
    "al_mabrouka",
    "al_yaarubiyah",
    "al_hawl",
    "al_himma",
    "al_ghazl",
    "al_kasra",
    "al_markada",
    "al_tayyana",
    "al_sweidiya",
    "al_khaldiya",
    "al_jawadiyah",
    "al_talaq",
  ],
  quneitra: [
    "quneitra",
    "khan_arnabah",
    "madinat_al_baath",
    "al_rafid",
    "jubata_al_khashab",
    "hadar",
    "al_qahtaniyah",
    "bir_ajam",
    "masharah",
    "naba_al_sakhr",
  ],
  as_suwayda: [
    "as_suwayda",
    "salkhad",
    "shahba",
    "qanawat",
    "al_qurayya",
    "ariqah",
    "al_mazraa",
    "thaala",
    "shagqa",
    "al_ruha",
  ],
};

const EN_LABELS: Record<string, string> = {
  damascus: "Damascus",
  rural_damascus: "Rural Damascus",
  aleppo: "Aleppo",
  homs: "Homs",
  hama: "Hama",
  latakia: "Latakia",
  tartous: "Tartous",
  idlib: "Idlib",
  daraa: "Daraa",
  deir_ezzor: "Deir ez-Zor",
  raqqa: "Raqqa",
  hasakah: "Al-Hasakah",
  quneitra: "Quneitra",
  as_suwayda: "As-Suwayda",
  mazzeh: "Mazzeh",
  kafrsouseh: "Kafr Souseh",
  barzeh: "Barzeh",
  meidan: "Meidan",
  ruken_al_din: "Rukneddine",
  bab_touma: "Bab Touma",
  bab_sharqi: "Bab Sharqi",
  tishreen: "Tishreen",
  al_qanawat: "Al-Qanawat",
  abu_rummaneh: "Abu Rummaneh",
  shaalan: "Shaalan",
  dummar: "Dummar",
  al_midan: "Al-Midan",
  kassaa: "Kassaa",
  old_damascus: "Old Damascus",
  qasioun: "Qasioun",
  adawi: "Adawi",
  al_amara: "Al-Amara",
  abu_jamal: "Abu Jamal",
  harika: "Al-Hariqa",
  douma: "Douma",
  harasta: "Harasta",
  zamalka: "Zamalka",
  jobar: "Jobar",
  qaboun: "Qaboun",
  madaya: "Madaya",
  zabadani: "Al-Zabadani",
  wafideen: "Al-Wafideen",
  sayyida_zeinab: "Sayyidah Zaynab",
  darayya: "Darayya",
  moadamiyeh: "Moadamiyat al-Sham",
  qatana: "Qatana",
  kiswah: "Al-Kiswah",
  dmeir: "Al-Dumayr",
  al_tall: "Al-Tall",
  arbin: "Arbin",
  haran_al_awamid: "Harran al-Awamid",
  yabroud: "Yabroud",
  an_nabk: "An-Nabk",
  deir_atiyah: "Deir Atiyah",
  jayrud: "Jayrud",
  assal_al_ward: "Assal al-Ward",
  salah_al_din: "Salah al-Din",
  hanano: "Hanano",
  ashrafiyeh: "Al-Ashrafiyah",
  aziziyeh: "Al-Aziziyah",
  seif_al_dawla: "Seif al-Dawla",
  al_furqan: "Al-Furqan",
  al_hamdaniya: "Al-Hamdaniya",
  al_sukari: "Al-Sukkari",
  al_shaar: "Al-Shaar",
  al_jamiliyeh: "Al-Jamiliyah",
  karm_al_jabal: "Karm al-Jabal",
  sheikh_maqsood: "Sheikh Maqsood",
  bustan_al_qasr: "Bustan al-Qasr",
  al_aziziyah: "Al-Aziziyah",
  new_aleppo: "New Aleppo",
  old_city: "Old City",
  sheikh_najjar: "Sheikh Najjar",
  khan_al_asal: "Khan al-Asal",
  ramousah: "Al-Ramousah",
  layramoun: "Al-Layramoun",
  al_layramoun: "Al-Layramoun",
  al_haydariyah: "Al-Haydariyah",
  al_inshaat: "Al-Inshaat",
  al_waer: "Al-Waer",
  al_hamra: "Al-Hamra",
  bab_tadmur: "Bab Tadmur",
  al_khaldiyeh: "Al-Khalidiyah",
  al_bayada: "Al-Bayada",
  deir_ba_alba: "Deir Baalba",
  ghouta: "Ghouta",
  al_qusur: "Al-Qusour",
  al_zahraa: "Al-Zahraa",
  al_nuzha: "Al-Nuzha",
  al_sabeel: "Al-Sabeel",
  al_hamidiyah: "Al-Hamidiyah",
  al_qarabis: "Al-Qarabis",
  al_karama: "Al-Karama",
  al_salam: "Al-Salam",
  al_ghouta: "Al-Ghouta",
  al_hosn: "Al-Husn",
  al_qaryatein: "Al-Qaryatayn",
  palmyra: "Palmyra",
  al_arbaeen: "Al-Arbaeen",
  al_nasiriya: "Al-Nasiriyah",
  al_kareem: "Al-Kareem",
  al_saboun: "Al-Saboun",
  al_baath: "Al-Baath",
  mhardeh: "Mhardeh",
  slimiyah: "Al-Salamiyah",
  kafr_zita: "Kafr Zita",
  latamina: "Al-Lataminah",
  taybat_al_imam: "Taybat al-Imam",
  soran: "Suran",
  kafr_nabudah: "Kafr Nabudah",
  halfaya: "Halfaya",
  maharda: "Maharda",
  qamhana: "Qamhana",
  al_latamna: "Al-Latamna",
  al_surmaniyah: "Al-Surmaniyah",
  al_mazzeh_hama: "Al-Mazzeh",
  al_suqailabiya: "Al-Suqaylabiyah",
  al_hamraa: "Al-Hamraa",
  al_ramleh: "Al-Ramleh",
  al_ziraa: "Al-Ziraa",
  corniche: "Corniche",
  qastal_maaf: "Qastal Maaf",
  jableh: "Jableh",
  qardaha: "Qardaha",
  slunfeh: "Slunfeh",
  baniyas: "Baniyas",
  al_haffa: "Al-Haffah",
  al_sheikh_daher: "Al-Sheikh Daher",
  al_daatour: "Al-Daatour",
  ras_al_basit: "Ras al-Bassit",
  kessab: "Kessab",
  al_sanamayn: "Al-Sanamayn",
  al_raml: "Al-Raml",
  al_bayda: "Al-Bayda",
  al_shamiya: "Al-Shamiyah",
  al_kabir: "Al-Kabir",
  al_safa: "Al-Safa",
  al_midan_latakia: "Al-Midan",
  al_sheikh_badr: "Al-Sheikh Badr",
  dreikish: "Dreikish",
  rabea: "Rabia",
  mashta_al_hilou: "Mashta al-Helu",
  bechmira: "Beshinmira",
  al_dreikish: "Al-Dreikish",
  al_kadmous: "Al-Qadmus",
  al_safsafah: "Al-Safsafah",
  al_sheikh_badr_center: "Sheikh Badr Center",
  al_kadmus: "Al-Qadmus",
  al_rastan_tartous: "Al-Rastan",
  al_sudan: "Al-Sudan",
  al_sisiya: "Al-Sisiya",
  al_hamra_tartous: "Al-Hamra",
  maarret_al_numan: "Maarat al-Numan",
  saraqib: "Saraqib",
  khan_sheikhoun: "Khan Shaykhun",
  jisir_al_shughur: "Jisr al-Shughur",
  binnish: "Binnish",
  taftanaz: "Taftanaz",
  araq: "Ariha",
  sarmin: "Sarmin",
  kafr_nabl: "Kafr Nabl",
  maaret_al_tamasrin: "Maarat Misrin",
  harem: "Harem",
  darkosh: "Darkush",
  salqin: "Salqin",
  al_dana: "Al-Dana",
  ram_hamdan: "Ram Hamdan",
  kafr_aya: "Kafr Aya",
  kafr_sajna: "Kafr Sajna",
  tal_karah: "Tal Karah",
  zardana: "Zardana",
  busra_al_sham: "Bosra",
  nawa: "Nawa",
  jasem: "Jasim",
  tafss: "Tafas",
  mzeireb: "Muzayrib",
  inkhilal: "Inkhil",
  hirak: "Al-Hirak",
  dael: "Dael",
  al_sheikh_maskin: "Al-Shaykh Maskin",
  namir: "Namir",
  ghabgab: "Ghabaghib",
  al_yadouda: "Al-Yadudah",
  al_tibneh: "Al-Tibni",
  tal_shihab: "Tell Shihab",
  khirbet_ghazaleh: "Khirbet Ghazaleh",
  al_harak: "Al-Harak",
  al_jiza: "Al-Jiza",
  al_manshiya: "Al-Manshiyah",
  al_mayadeen: "Al-Mayadin",
  al_bukamal: "Abu Kamal",
  al_busayra: "Al-Busayrah",
  al_susah: "Al-Susah",
  khasham: "Khasham",
  al_husseiniyah: "Al-Husseiniyah",
  al_jura: "Al-Jura",
  al_quriya: "Al-Quriyah",
  al_hawayej: "Al-Hawayij",
  al_tayana: "Al-Tayanah",
  al_tabni: "Al-Tibni",
  al_shuhail: "Al-Shuhail",
  al_abu_kamal: "Abu Kamal",
  al_husainiya: "Al-Husainiyah",
  al_jezira: "Al-Jazira",
  al_dhula: "Al-Dhula",
  al_baghouz: "Al-Baghuz",
  al_salihiyah: "Al-Salihiyah",
  al_omar: "Al-Omar",
  tal_abyad: "Tell Abyad",
  al_tabqa: "Al-Thawrah (Tabqa)",
  al_mansoura: "Al-Mansurah",
  al_karamah: "Al-Karamah",
  al_hanida: "Al-Hanida",
  al_kasrat: "Al-Kasrat",
  al_resh: "Al-Resh",
  al_hisba: "Al-Hisba",
  al_rashid: "Al-Rashid",
  al_jurneyyah: "Al-Jurniyah",
  al_sabkha: "Al-Sabkhah",
  al_hol: "Al-Hawl",
  al_rasafa: "Al-Rusafa",
  al_sharakrak: "Al-Sharakrak",
  al_khafsa: "Al-Khafsa",
  al_masrab: "Al-Masrab",
  al_tabaqa_dam: "Tabqa Dam",
  al_qadisiya: "Al-Qadisiyah",
  qamishli: "Qamishli",
  malikiya: "Al-Malikiyah",
  ras_al_ayn: "Ras al-Ayn",
  al_shaddadi: "Al-Shaddadah",
  amuda: "Amuda",
  derbasiya: "Al-Darbasiyah",
  tirbespi: "Al-Qahtaniyah (Tirbespi)",
  al_mabrouka: "Al-Mabrukah",
  al_yaarubiyah: "Al-Yaarubiyah",
  al_hawl: "Al-Hawl",
  al_himma: "Al-Himma",
  al_ghazl: "Al-Ghazl",
  al_kasra: "Al-Kasrah",
  al_markada: "Markada",
  al_tayyana: "Al-Tayanah",
  al_sweidiya: "Al-Suwaydiyah",
  al_khaldiya: "Al-Khalidiyah",
  al_jawadiyah: "Al-Jawadiyah",
  al_talaq: "Al-Talaq",
  khan_arnabah: "Khan Arnabah",
  madinat_al_baath: "Baath City",
  al_rafid: "Al-Rafid",
  jubata_al_khashab: "Jubata al-Khashab",
  hadar: "Hadar",
  al_qahtaniyah: "Al-Qahtaniyah",
  bir_ajam: "Bir Ajam",
  masharah: "Masharah",
  naba_al_sakhr: "Naba al-Sakhr",
  salkhad: "Salkhad",
  shahba: "Shahba",
  qanawat: "Qanawat",
  al_qurayya: "Al-Qurayya",
  ariqah: "Ariqah",
  al_mazraa: "Al-Mazraa",
  thaala: "Thaala",
  shagqa: "Shaqqa",
  al_ruha: "Al-Ruha",
};

const AR_LABELS: Record<string, string> = {
  damascus: "دمشق",
  rural_damascus: "ريف دمشق",
  aleppo: "حلب",
  homs: "حمص",
  hama: "حماة",
  latakia: "اللاذقية",
  tartous: "طرطوس",
  idlib: "إدلب",
  daraa: "درعا",
  deir_ezzor: "دير الزور",
  raqqa: "الرقة",
  hasakah: "الحسكة",
  quneitra: "القنيطرة",
  as_suwayda: "السويداء",
  mazzeh: "المزة",
  kafrsouseh: "كفرسوسة",
  barzeh: "برزة",
  meidan: "الميدان",
  ruken_al_din: "ركن الدين",
  bab_touma: "باب توما",
  bab_sharqi: "باب شرقي",
  tishreen: "تشرين",
  al_qanawat: "القنوات",
  abu_rummaneh: "أبو رمانة",
  shaalan: "الشعلان",
  dummar: "دمر",
  al_midan: "الميدان",
  kassaa: "القصاع",
  old_damascus: "دمشق القديمة",
  qasioun: "قاسيون",
  adawi: "العدوي",
  al_amara: "العمارة",
  abu_jamal: "أبو جمال",
  harika: "الحريقة",
  douma: "دوما",
  harasta: "حرستا",
  zamalka: "زملكا",
  jobar: "جوبر",
  qaboun: "القابون",
  madaya: "مضايا",
  zabadani: "الزبداني",
  wafideen: "مخيم الوافدين",
  sayyida_zeinab: "السيدة زينب",
  darayya: "داريا",
  moadamiyeh: "معضمية الشام",
  qatana: "قطنا",
  kiswah: "الكسوة",
  dmeir: "الضمير",
  al_tall: "التل",
  arbin: "عربين",
  haran_al_awamid: "حران العواميد",
  yabroud: "يبرود",
  an_nabk: "النبك",
  deir_atiyah: "دير عطية",
  jayrud: "جيرود",
  assal_al_ward: "عسال الورد",
  salah_al_din: "صلاح الدين",
  hanano: "هنانو",
  ashrafiyeh: "الأشرفية",
  aziziyeh: "العزيزية",
  seif_al_dawla: "سيف الدولة",
  al_furqan: "الفرقان",
  al_hamdaniya: "الحمدانية",
  al_sukari: "السكري",
  al_shaar: "الشعار",
  al_jamiliyeh: "الجميلية",
  karm_al_jabal: "كرم الجبل",
  sheikh_maqsood: "الشيخ مقصود",
  bustan_al_qasr: "بستان القصر",
  al_aziziyah: "العزيزية",
  new_aleppo: "حلب الجديدة",
  old_city: "المدينة القديمة",
  sheikh_najjar: "الشيخ نجار",
  khan_al_asal: "خان العسل",
  ramousah: "الراموسة",
  layramoun: "الليرمون",
  al_layramoun: "الليرمون",
  al_haydariyah: "الحيدرية",
  al_inshaat: "الإنشاءات",
  al_waer: "الوعر",
  al_hamra: "الحمراء",
  bab_tadmur: "باب تدمر",
  al_khaldiyeh: "الخالدية",
  al_bayada: "البياضة",
  deir_ba_alba: "دير بعلبة",
  ghouta: "الغوطة",
  al_qusur: "القصور",
  al_zahraa: "الزهراء",
  al_nuzha: "النزهة",
  al_sabeel: "السبيل",
  al_hamidiyah: "الحميدية",
  al_qarabis: "القرابيص",
  al_karama: "الكرامة",
  al_salam: "السلام",
  al_ghouta: "الغوطة",
  al_hosn: "الحصن",
  al_qaryatein: "القريتين",
  palmyra: "تدمر",
  al_arbaeen: "الأربعين",
  al_nasiriya: "الناصرية",
  al_kareem: "الكريم",
  al_saboun: "الصابون",
  al_baath: "البعث",
  mhardeh: "محردة",
  slimiyah: "السلمية",
  kafr_zita: "كفرزيتا",
  latamina: "اللطامنة",
  taybat_al_imam: "طيبة الإمام",
  soran: "صوران",
  kafr_nabudah: "كفرنبودة",
  halfaya: "حلفايا",
  maharda: "محردة",
  qamhana: "قمحانة",
  al_latamna: "اللطامنة",
  al_surmaniyah: "السرمانية",
  al_mazzeh_hama: "المزة",
  al_suqailabiya: "السقيلبية",
  al_hamraa: "الحمراء",
  al_ramleh: "الرملة",
  al_ziraa: "الزراعة",
  corniche: "الكورنيش",
  qastal_maaf: "قسطل معاف",
  jableh: "جبلة",
  qardaha: "القرداحة",
  slunfeh: "صلنفة",
  baniyas: "بانياس",
  al_haffa: "الحفة",
  al_sheikh_daher: "الشيخ ضاهر",
  al_daatour: "الدعتور",
  ras_al_basit: "رأس البسيط",
  kessab: "كسب",
  al_sanamayn: "الصنمين",
  al_raml: "الرمل",
  al_bayda: "البيضا",
  al_shamiya: "الشامية",
  al_kabir: "الكبير",
  al_safa: "الصفا",
  al_midan_latakia: "الميدان",
  al_sheikh_badr: "الشيخ بدر",
  dreikish: "دريكيش",
  rabea: "الربيعة",
  mashta_al_hilou: "مشتى الحلو",
  bechmira: "بشمرا",
  al_dreikish: "الدريكيش",
  al_kadmous: "القدموس",
  al_safsafah: "الصفصافة",
  al_sheikh_badr_center: "مركز الشيخ بدر",
  al_kadmus: "القدموس",
  al_rastan_tartous: "الرستن",
  al_sudan: "السودان",
  al_sisiya: "السيسية",
  al_hamra_tartous: "الحمراء",
  maarret_al_numan: "معرة النعمان",
  saraqib: "سراقب",
  khan_sheikhoun: "خان شيخون",
  jisir_al_shughur: "جسر الشغور",
  binnish: "بنش",
  taftanaz: "تفتناز",
  araq: "أريحا",
  sarmin: "سرمين",
  kafr_nabl: "كفرنبل",
  maaret_al_tamasrin: "معرة مصرين",
  harem: "حارم",
  darkosh: "دركوش",
  salqin: "سلقين",
  al_dana: "الدانا",
  ram_hamdan: "رام حمدان",
  kafr_aya: "كفر عايا",
  kafr_sajna: "كفر سجنة",
  tal_karah: "تل الكرام",
  zardana: "زردنا",
  busra_al_sham: "بصرى الشام",
  nawa: "نوى",
  jasem: "جاسم",
  tafss: "طفس",
  mzeireb: "مزيريب",
  inkhilal: "إنخل",
  hirak: "الحراك",
  dael: "داعل",
  al_sheikh_maskin: "الشيخ مسكين",
  namir: "نامر",
  ghabgab: "غباغب",
  al_yadouda: "اليادودة",
  al_tibneh: "التبنة",
  tal_shihab: "تل شهاب",
  khirbet_ghazaleh: "خربة غزالة",
  al_harak: "الحراك",
  al_jiza: "الجيزة",
  al_manshiya: "المنشية",
  al_mayadeen: "الميادين",
  al_bukamal: "البوكمال",
  al_busayra: "البصيرة",
  al_susah: "السوسة",
  khasham: "خشام",
  al_husseiniyah: "الحسينية",
  al_jura: "الجورة",
  al_quriya: "القورية",
  al_hawayej: "الحوايج",
  al_tayana: "الطيانة",
  al_tabni: "التبني",
  al_shuhail: "الشحيل",
  al_abu_kamal: "البوكمال",
  al_husainiya: "الحسينية",
  al_jezira: "الجزيرة",
  al_dhula: "الضلع",
  al_baghouz: "الباغوز",
  al_salihiyah: "الصالحية",
  al_omar: "العمر",
  tal_abyad: "تل أبيض",
  al_tabqa: "الطبقة",
  al_mansoura: "المنصورة",
  al_karamah: "الكرامة",
  al_hanida: "الهنيدة",
  al_kasrat: "الكسرات",
  al_resh: "الرش",
  al_hisba: "الحسبة",
  al_rashid: "الرشيد",
  al_jurneyyah: "الجرنية",
  al_sabkha: "السبخة",
  al_hol: "الهول",
  al_rasafa: "الرصافة",
  al_sharakrak: "الشركراك",
  al_khafsa: "الخفسة",
  al_masrab: "المسرب",
  al_tabaqa_dam: "سد الطبقة",
  al_qadisiya: "القادسية",
  qamishli: "القامشلي",
  malikiya: "المالكية",
  ras_al_ayn: "رأس العين",
  al_shaddadi: "الشدادي",
  amuda: "عامودا",
  derbasiya: "الدرباسية",
  tirbespi: "القحطانية",
  al_mabrouka: "المبروكة",
  al_yaarubiyah: "اليعربية",
  al_hawl: "الهول",
  al_himma: "الحمة",
  al_ghazl: "الغزل",
  al_kasra: "الكسرة",
  al_markada: "مركدة",
  al_tayyana: "الطيانة",
  al_sweidiya: "السويدية",
  al_khaldiya: "الخالدية",
  al_jawadiyah: "الجوادية",
  al_talaq: "الطلق",
  khan_arnabah: "خان أرنبة",
  madinat_al_baath: "مدينة البعث",
  al_rafid: "الرفيد",
  jubata_al_khashab: "جباتا الخشب",
  hadar: "حضر",
  al_qahtaniyah: "القحطانية",
  bir_ajam: "بئر عجم",
  masharah: "ممتنة (مشارق)",
  naba_al_sakhr: "نبع الصخر",
  salkhad: "صلخد",
  shahba: "شهبا",
  qanawat: "قنوات",
  al_qurayya: "القريا",
  ariqah: "عريقة",
  al_mazraa: "المزرعة",
  thaala: "الثعلة",
  shagqa: "شقا",
  al_ruha: "الرحى",
};

const LABELS_BY_LANGUAGE: Record<"en" | "ar", Record<string, string>> = {
  en: EN_LABELS,
  ar: AR_LABELS,
};

function fallbackLabel(key: string): string {
  return key
    .split("_")
    .filter(Boolean)
    .map((part) => part.charAt(0).toUpperCase() + part.slice(1))
    .join(" ");
}

export function getGovernoratesWithCities(
  language: string,
): GovernorateWithCities[] {
  const normalizedLanguage = language?.toLowerCase().startsWith("ar")
    ? "ar"
    : "en";
  const labels = LABELS_BY_LANGUAGE[normalizedLanguage];
  let cityId = 1;

  return Object.entries(GOVERNORATE_CITIES).map(([governorateKey, cityKeys]) => ({
    id: governorateKey,
    name: labels[governorateKey] ?? fallbackLabel(governorateKey),
    cities: cityKeys.map((cityKey) => ({
      id: cityId++,
      name: labels[cityKey] ?? fallbackLabel(cityKey),
    })),
  }));
}
